### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by DickensJuma**
>Apple.com Clone 

## Project Specifics

  -Have completed the project using **backgrounds** and **gradients**.
  -Have used the grid, flex, and box-model.
  -Have followed the **github flow** and created a **feature** branch that hosts my code.
  -Have tested my code using **stylelint**.

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @DickensJuma, you have really done a great job 👍 **congratulations** 🙂 Before we proceed, let us improve our project a bit 😄 . Find comments below:
- Let us add the ```hover``` effect to the nav list items
- Let us fix the ```<div class="gallery">``` . Since our main focus is using ```background``` and ```gradients``` I highly recommend we use ```<div class=" one">``` to set our background and wrap each of ```<div>``` with the ```<a>``` so we can click on it.
bt
- Let us add a link to the copyright text
bt1
- Let us refactor our CSS code, we can group elements with the same property and value like the image below
tk


Kindly make these changes and submit another code review 😄 
_Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by uryelah** [comment]
Hello **Juma Juma**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all, good job at fixing the required changes from the last code review 🎇**
It appears that somethings broke in the process though.

---------    

### Required changes 🛠 

- [ ] The images at `.gallery` are not showing up. Please make sure the background images are visible.

- [ ] The `#info1` and `#info2` texts are not visible. Please make sure they show up.

- [ ] The search icon in the navbar is spilling out of the input. Please[ check the original page](https://web.archive.org/web/20140301004610/http://www.apple.com/) to see how it's aligned inside the input.

- [ ] Please don't use ids to style in CSS.[ Read this article ](https://dev.to/clairecodes/reasons-not-to-use-ids-in-css-4ni4)on why you should use classes instead.

- [ ] You have a couple of errors in your HTML validation. Please test your markup at [https://validator.w3.org/nu/](https://validator.w3.org/nu/) and fixes the present errors.

This is how the project looked when I opened it vs the original site:

Screenshot_2020-03-15 apple
Screenshot_2020-03-15 Apple(1)


----

**Kindly fix the REQUIRED above issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by lekegitrepo** [comment]
### Hi @DickensJuma 👏 👏 
### You have done a good job. However, you forget to enable stickler for the repo and the use of overflow hidden cut the height of the page

**_This is the image of the page in a maximized browser window:_**

image

**_Fix these two issues and submit for review_**

**_You can contact me on slack if you have any doubt or question_**

### Reviewed by: Temitayo Adeleke

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require changes.

**Comment by uryelah** [comment]
Good job fixing the last two changes Juma!

### Your project is approved! 🎊 🥅 💛 
-------
### 
**You may close this Pull Request and merge the changes**

-------

**Good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
